feat: get account info and get account balance
stone-co/the-amazing-ledger pull request #39
Opened 2020-11-11 19:37 UTC by juceliofloresta

- Update rpc SDK
- update rpc protofile :file_cabinet: 
- AccountInfo vs AccountName vs AccountBalance vs AccountPath :boxing_glove: 
  - AccountInfo: populate from database query, have total credit, total debit and version. :information_source:  
  - AccountName: struct to control account path formated :video_game: 
  - AccountBalance : structure to response rpc and http :email: 
  - AccountPath: literal string with account name string. :capital_abcd: 

- cmd name to server

Issue: #28

2020-11-11 21:34 UTC, alexgarzao commented on clients/grpc/examples/get_account_balance.go
> +	// Define a new transaction with 3 entries
3 or 2?

2020-11-11 23:00 UTC, alexgarzao requested changes

2020-11-11 23:14 UTC, alexgarzao commented on pkg/command-handler/domain/ledger/entities/errors.go
> +	ErrNotFound                = errors.New("object not found")
Usually, generic errors inside the domain must be avoided.

2020-11-11 23:16 UTC, alexgarzao commented on pkg/command-handler/domain/ledger/repository.go
> +	GetAccountInfo(ctx context.Context, accountName *entities.AccountName) (*entities.AccountInfo, error)
accountName must be a pointer?

2020-11-11 23:18 UTC, alexgarzao commented on pkg/command-handler/domain/ledger/transactions.go
> +	GetAccountInfo(ctx context.Context, accountPath string) (*entities.AccountInfo, error)
accountPath must be an AccountName type?

2020-11-11 23:19 UTC, alexgarzao commented on pkg/command-handler/domain/ledger/usecase/get_account_info.go
> +	"github.com/jackc/pgx/v4"
Line space is missing here

2020-11-11 23:22 UTC, alexgarzao commented on pkg/command-handler/domain/ledger/usecase/get_account_info_test.go
> +	"github.com/stone-co/the-amazing-ledger/pkg/command-handler/domain/ledger/entities"
Missing line space here

2020-11-11 23:33 UTC, alexgarzao commented on pkg/command-handler/domain/ledger/usecase/get_account_info_test.go
> +	})
There are tests to check for errors?

2020-11-12 00:36 UTC, alexgarzao requested changes

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/db/postgres/get_account_info.go
> +		&empty,
I'm not sure, but I think that is possible to pass nil instead of empty: https://github.com/jackc/pgx/blob/93c6b60429e13e0016665214dca2c6382982cf99/rows.go#L212

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/db/postgres/get_account_info.go
> +		creditOperation,
It's not wrong but is a good practice to pass the keys before.

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +type AccountNotFoundRequest struct {
In reality, I think that it's wrong on the save transaction handler. We need to review this.

We need to have a common error struct to use when necessary (or something like that).

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +		"handler": "Get Account Balance",
Without spaces in the handler name.

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +	decodedAccountPath, err := url.QueryUnescape(accountPath)
Maybe, try to change the logic here. We are receiving an encoded path, but we need a path.

encondedAccountPath := vars["account_path"]
accountPath, err := url.QueryUnescape(encodedAccountPath)

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +		log.WithError(err).Error("Query Unescape error")
In the case of error, it's necessary to specify the error to be returned on the API.

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +		if err == entities.ErrNotFound {
It's possible to simplify this a little bit. I can help you.

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +			w.WriteHeader(http.StatusInternalServerError)
In this case, it's not necessary (line 54).

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +		CurrentVersion: uint64(accountInfo.CurrentVersion.Current()),
We can have a method in CurrentVersion to cast to uint64. For example:

CurrentVersion: accountInfo.CurrentVersion.ToInt64()

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/http/transactions/get_account_balance.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
http.Error?

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/rpc/proto/ledger.proto
> +  rpc GetAccountBalance(GetAccountInfoRequest) returns (GetAccountInfoResponse);
If the method is GetAccountBalance, I think that the message must be GetAccountBalanceRequest and GetAccountBalanceReponse.

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/rpc/proto/ledger.proto
> +  int64 current_version = 2; // To deal with optimistic lock.
uint64

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/rpc/proto/ledger.proto
> +  string account_id = 1; // Represents an account.
account_path instead ofaccount_id? Or is better for us to wait a little more to rename all name in one specific PR?

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/rpc/transactions/get_account_balance.go
> +	accountID := in.AccountId
accountPath?

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/rpc/transactions/get_account_balance.go
> +			log.WithError(err).Error("object not found")
account not found?

2020-11-12 00:36 UTC, alexgarzao commented on pkg/gateways/rpc/transactions/get_account_balance.go
> +		log.WithError(err).Error(" error getting account info")
The word " error " is not necessary here.

2020-11-12 00:36 UTC, alexgarzao commented on clients/grpc/examples/get_account_balance.go
> +package main
We need more tests here. For example, create more than 1 transaction, with 2 and 3 entries in each transaction, and after that, get the balance and check if is ok.

2020-11-12 14:16 UTC, alexgarzao commented on pkg/gateways/db/postgres/get_account_info.go
> +		&empty,
Is necessary to create the indexes to this query in our migrations.

2020-11-12 19:32 UTC, juceliofloresta commented on clients/grpc/examples/get_account_balance.go
> +	// Define a new transaction with 3 entries
It's two.

2020-11-12 19:36 UTC, juceliofloresta commented on clients/grpc/examples/get_account_balance.go
> +	saveTransactionToGetAccountTest(log, conn)
Make sense, func and test are merged.

2020-11-12 21:40 UTC, juceliofloresta commented on clients/grpc/examples/get_account_balance.go
> +	accountBalance, err := conn.GetAccountBalance(context.Background(), a)
LGTM, done :+1:

2020-11-13 12:26 UTC, juceliofloresta commented on clients/grpc/examples/get_account_balance.go
> +	AssertEqual(entities.ErrNotFound, err)
great! thanks for suggestion. :heavy_check_mark:

2020-11-13 16:35 UTC, juceliofloresta commented on pkg/command-handler/domain/ledger/transactions.go
> +	GetAccountInfo(ctx context.Context, accountPath string) (*entities.AccountInfo, error)
make sense, we'll use AccountName type.

2020-11-13 16:37 UTC, juceliofloresta commented on pkg/gateways/rpc/proto/ledger.proto
> +  rpc GetAccountBalance(GetAccountInfoRequest) returns (GetAccountInfoResponse);
done :heavy_check_mark:

2020-11-13 16:39 UTC, juceliofloresta commented on pkg/gateways/rpc/proto/ledger.proto
> +  string account_id = 1; // Represents an account.
I think that we can rename to account_path, because ID have a mean in AccountName structure.

2020-11-13 16:57 UTC, juceliofloresta commented on pkg/gateways/rpc/transactions/get_account_balance.go
> +	accountID := in.AccountId
:dart: yeah. :heavy_check_mark:

2020-11-13 17:28 UTC, juceliofloresta commented on pkg/command-handler/domain/ledger/repository.go
> +	GetAccountInfo(ctx context.Context, accountName *entities.AccountName) (*entities.AccountInfo, error)
nope :x:

2020-11-13 20:20 UTC, juceliofloresta commented on pkg/gateways/db/postgres/get_account_info.go
> +		    END) AS total_debit
yes, i paste whit legacy format. :heavy_check_mark:

2020-11-16 13:35 UTC, juceliofloresta commented on pkg/command-handler/domain/ledger/entities/errors.go
> +	ErrNotFound                = errors.New("object not found")
:heavy_check_mark:

2020-11-18 15:13 UTC, alexgarzao approved these changes

2020-11-18 15:13 UTC, duarte2025 approved these changes

2020-11-18 15:27 UTC, merged