feat: account history
stone-co/the-amazing-ledger pull request #66
Opened 2021-01-14 15:47 UTC by juceliofloresta

## Feature Account History #32

```diff
# This feature implements the History of an Account when giving an Account Path.

# Repository and Use Case
+ Get a history of an account

# Value Objects
+ AccountHistory
+ EntryHistory

+ Update RPC SDK with GetAccountHistory method.

- It wasn't implementing the data range filter.

! SDK users must update your client.

@@ Have a great code review xD @@
```

2021-02-09 13:45 UTC, alexgarzao requested changes
Very nice PR!

We must use NewRelic, when necessary. And there is a possible panic during tests.

2021-02-09 13:45 UTC, alexgarzao commented on clients/grpc/examples/get_account_history.go
> +	accountHistory, err := conn.GetAccountHistory(context.Background(), accountPathOne)
Assert err == nil after GetAccountHistory to avoid panic during test execution.

2021-02-09 13:45 UTC, alexgarzao commented on clients/grpc/examples/get_account_history.go
> +	accountHistory, err := conn.GetAccountHistory(context.Background(), accountPathOne)
And test to assure that accountHistory has 2 entries.

2021-02-09 13:45 UTC, alexgarzao commented on clients/grpc/examples/get_account_history.go
> +
I think that is a good idea to check for accountPathTwo history too

2021-02-09 13:45 UTC, alexgarzao commented on clients/grpc/examples/get_account_history.go
> +	accountHistory, err := conn.GetAccountHistory(context.Background(), accountPathOne)
Check err and accountHistory size here to avoid panic

2021-02-11 21:48 UTC, juceliofloresta commented on clients/grpc/examples/get_account_history.go
> +	accountHistory, err := conn.GetAccountHistory(context.Background(), accountPathOne)
:+1: :heavy_check_mark:

2021-02-11 21:49 UTC, juceliofloresta commented on clients/grpc/examples/get_account_history.go
> +	accountHistory, err := conn.GetAccountHistory(context.Background(), accountPathOne)
:+1: :heavy_check_mark:

2021-02-11 21:49 UTC, juceliofloresta commented on clients/grpc/examples/get_account_history.go
> +
:+1: :heavy_check_mark:

2021-02-12 14:00 UTC, alexgarzao approved these changes

2021-02-12 19:51 UTC, alexmourapb approved these changes

2021-02-18 21:31 UTC, merged